### ISSUE TITLE
[Lifecycle] Install fails if "linkerd" namespace already exists

### ISSUE THREAD

**Issue by leecalcote** [meshery/meshery-linkerd#184]
**Description**
In an environment with "linkerd" namespace already present, deployment of Linkerd fails.

**Expected Behavior**
Linkerd should be installed to the existing namespace.

**Logs**
```
Error with linkerd operation: Error fetching mesh manifest: Can't install the Linkerd control plane in the 'linkerd' namespace. Reason: ConfigMap/linkerd-config already exists. If this is expected, use the --ignore-cluster flag to continue the installation.
```

**Enviroment:**
 - Meshery Version: v0.5.0
 - Adapter Version:

**Comment by leecalcote** [comment]
@Aisuko can you look into this? // @utkarsh-pro

**Comment by leecalcote** [comment]
@kumarabd Logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x16897ee]

goroutine 76 [running]:
github.com/layer5io/meshkit/utils/kubernetes.constructObject(0x1f1e3e0, 0xc000866580, 0xc000618660, 0x27, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/layer5io/meshkit@v0.1.31/utils/kubernetes/apply-manifest.go:107 +0xbe
github.com/layer5io/meshkit/utils/kubernetes.(*Client).ApplyManifest(0xc0006a9c00, 0xc000b76000, 0x1547f, 0x16000, 0x0, 0x0, 0x7f2b467f0000, 0x3, 0x0)
	/go/pkg/mod/github.com/layer5io/meshkit@v0.1.31/utils/kubernetes/apply-manifest.go:48 +0x1d9
github.com/layer5io/meshery-linkerd/linkerd.(*Linkerd).applyManifest(0xc000128c80, 0xc000b76000, 0x1547f, 0x16000, 0x15400, 0x0, 0x0, 0x0, 0x414b8e)
	/github.com/layer5io/meshery-linkerd/linkerd/install.go:93 +0x135
github.com/layer5io/meshery-linkerd/linkerd.(*Linkerd).installLinkerd(0xc000128c80, 0xc000a57e00, 0xc0002753c0, 0xd, 0xc000274f67, 0x7, 0x16a197f, 0xc000773bc0, 0x1976360, 0xc000548000)
	/github.com/layer5io/meshery-linkerd/linkerd/install.go:47 +0x529
github.com/layer5io/meshery-linkerd/linkerd.(*Linkerd).ApplyOperation.func1(0xc000108128, 0xc000274f60, 0x7, 0xc000274f67, 0x7, 0xc000274f80, 0x8, 0x0, 0x0, 0x0, ...)
	/github.com/layer5io/meshery-linkerd/linkerd/linkerd.go:48 +0xca
created by github.com/layer5io/meshery-linkerd/linkerd.(*Linkerd).ApplyOperation
	/github.com/layer5io/meshery-linkerd/linkerd/linkerd.go:46 +0x43f
```
